### ISSUE TITLE
InvalidStateException: Invalid state: INITIALISED; allowed: [STARTED]

### ISSUE THREAD

**Issue by devent** [m88i/nexus-operator#227]
**Describe the bug**

The error pops out: Invalid state: INITIALISED; allowed: [STARTED] at the page repositories. No repositories can be created.

**To Reproduce**
1. install operator
2. install nexus
3. login per admin default credentials
4. run the wizard
5. go to Repositories page

**Expected behavior**

No error, repositories can be created.

**Environment**

Kubernetes deployment.

Operator v0.6.0

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

```
replicas: 1

useRedHatImage: false

persistence:
  persistent: true
  storageClass: managed-nfs-storage
  volumeSize: 50Gi
  extraVolumes:
    - name: logback
      mountPath: /nexus-data/etc/logback
      emptyDir:
        medium: ""

networking:
  expose: false
```

Log:

```
2022-04-27 08:45:25,353+0000 ERROR [qtp2072319896-1092] admin org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method: coreui_Repository.coreui_Repository_readStatus, java-method: org.sonatype.nexus.coreui.RepositoryComponent.readStatus
org.sonatype.nexus.common.stateguard.InvalidStateException: Invalid state: INITIALISED; allowed: [STARTED]
        at org.sonatype.nexus.common.stateguard.StateGuard._ensure(StateGuard.java:115)
        at org.sonatype.nexus.common.stateguard.StateGuard.access$1(StateGuard.java:108)
        at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:271)
        at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:54)
```

**Comment by ricardozanini** [comment]
Hi, @devent. Many thanks for opening this bug. Can you try using an older Nexus Server image? Not sure how this error relates to the operator's deployment. I do not see a file system error or configuration. Have you reported to Nexus? Is this error happening locally (docker run <nexus-server-image>)?

**Comment by devent** [comment]
I just restarted Nexus and now the repositories are there. I will close this.

**Comment by FlowBreeze** [comment]
Same issue here
Nexus opeator got error state: INITIALISED when first time bootstarp
The current solution is delete nexus pod and wait it to restart
```
kubectl delete pod <nexus_pod>
```

And may this issue open to help others or wait a better solution?

**Comment by ricardozanini** [comment]
@FlowBreeze, this seems to me a problem on the Nexus side, not in the operator. I'd like to understand a little better what is happening; maybe can you open an issue in their JIRA?

**Comment by FlowBreeze** [comment]
Sorry for that @ricardozanini
I haven't test Nexus works on local machine or not
So maybe it's not a good idea for me to open an issue on Nexus

**Comment by ricardozanini** [comment]
@FlowBreeze can you please link the issue here once you open it?

I'm reopening this issue to follow up.
