### ISSUE TITLE
Nexus fails when deployed without persistence

### ISSUE THREAD

**Issue by sutaakar** [m88i/nexus-operator#25]
When I deploy Nexus without persistence then the Nexus pod fails with "Permission denied" issues.

Example CR:
```
apiVersion: apps.m88i.io/v1alpha1
kind: Nexus
metadata:
  name: nexus3
spec:
  replicas: 1
  useRedHatImage: false
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
  persistence:
    persistent: false
  networking:
    expose: true
```
In the log I can see:
```
id: cannot find name for user ID 1000650000
Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
OpenJDK 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to Permission denied

java.io.FileNotFoundException: ../sonatype-work/nexus3/tmp/i4j_tA0O_LqRVFNhWb_IlDQiAGNa5vA=.lock (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.install4j.runtime.launcher.util.SingleInstance.check(SingleInstance.java:72)
	at com.install4j.runtime.launcher.util.SingleInstance.checkForCurrentLauncher(SingleInstance.java:31)
	at com.install4j.runtime.launcher.UnixLauncher.checkSingleInstance(UnixLauncher.java:88)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:67)
...
```

**Comment by sutaakar** [comment]
Deploying Nexus with persistence works correctly.

**Comment by ricardozanini** [comment]
It seems that the image requires a PV mounted :(

I’ll take a look into it to understand if we can run the image without volume.

**Comment by ricardozanini** [comment]
Fixed here:
https://github.com/m88i/nexus-operator/pull/35
